import {
  sequelize,
  User,
  Aset,
  PusatData,
  Riwayat,
  Notifikasi,
} from "./src/models/index.js";

async function seedAll() {
  try {
    // Drop and recreate all tables
    await sequelize.query('DROP TABLE IF EXISTS "notifikasi" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "riwayat" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "aset" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "pusat_data" CASCADE');
    await sequelize.query('DROP TABLE IF EXISTS "users" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_users_role" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_aset_status" CASCADE');
    await sequelize.query(
      'DROP TYPE IF EXISTS "enum_aset_jenis_masalah" CASCADE',
    );
    await sequelize.query('DROP TYPE IF EXISTS "enum_riwayat_aksi" CASCADE');
    await sequelize.query('DROP TYPE IF EXISTS "enum_notifikasi_tipe" CASCADE');
    await sequelize.query(
      'DROP TYPE IF EXISTS "enum_notifikasi_kategori" CASCADE',
    );
    console.log("🗑️  Dropped all existing tables and enums");

    await sequelize.sync({ force: true });
    console.log("✅ Database synced with fresh schema");

    // ===== SEED USERS =====
    console.log("\n📦 Seeding users...");
    const users = [
      {
        username: "admin_bpka",
        password: "admin123",
        email: "admin_bpka@simaset.com",
        nama_lengkap: "Ir. Hadi Santoso, M.Si",
        role: "admin_bpka",
        jabatan: "Kepala Bidang Aset",
        instansi: "BPKA Kota Pasuruan",
        nip: "197805152005011003",
        status_aktif: true,
      },
      {
        username: "admin_bpn",
        password: "admin123",
        email: "admin_bpn@simaset.com",
        nama_lengkap: "Drs. Agus Prasetyo, M.H",
        role: "admin_bpn",
        jabatan: "Kepala Seksi Penanganan Masalah",
        instansi: "BPN Kota Pasuruan",
        nip: "198001082006041002",
        status_aktif: true,
      },
      {
        username: "bpka",
        password: "bpka123",
        email: "bpka@simaset.com",
        nama_lengkap: "Siti Rahayu, S.E",
        role: "bpka",
        jabatan: "Operator Data Aset",
        instansi: "BPKA Kota Pasuruan",
        nip: "199003152018012001",
        status_aktif: true,
      },
      {
        username: "bpn_user",
        password: "bpn123",
        email: "bpn@simaset.com",
        nama_lengkap: "Rizky Firmansyah, S.H",
        role: "bpn",
        jabatan: "Verifikator Pertanahan",
        instansi: "BPN Kota Pasuruan",
        nip: "199205202019031005",
        status_aktif: true,
      },
    ];

    const createdUsers = {};
    for (const userData of users) {
      const user = await User.create(userData);
      createdUsers[userData.role] = user.id_user;
      console.log(`  ✅ Created user: ${userData.username} (${userData.role})`);
    }

    // ===== SEED PUSAT DATA (BPKA) =====
    console.log("\n📦 Seeding Pusat Data (BPKA)...");
    const pusatDataItems = [
      {
        kode_barang: "01.01.11.04.01",
        nama_barang: "Tanah Kantor Kelurahan Purworejo",
        nibar: "NB-001-2020",
        luas: 1250.0,
        alamat:
          "Jl. Panglima Sudirman No. 10, Kel. Purworejo, Kec. Purworejo, Kota Pasuruan",
        nilai_perolehan: 2500000000,
        no_sertifikat: "HM-001/Purworejo",
        tanggal: "2020-03-15",
        opd: "Kelurahan Purworejo",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.02",
        nama_barang: "Tanah Puskesmas Kebonsari",
        nibar: "NB-002-2019",
        luas: 2100.5,
        alamat:
          "Jl. Dr. Wahidin No. 32, Kel. Kebonsari, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 4200000000,
        no_sertifikat: "HP-003/Kebonsari",
        tanggal: "2019-07-22",
        opd: "Dinas Kesehatan Kota Pasuruan",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.03",
        nama_barang: "Tanah SDN Kandangsapi 1",
        nibar: "NB-003-2018",
        luas: 3500.0,
        alamat:
          "Jl. Veteran No. 45, Kel. Kandangsapi, Kec. Bugul Kidul, Kota Pasuruan",
        nilai_perolehan: 5250000000,
        no_sertifikat: "HP-012/Kandangsapi",
        tanggal: "2018-01-10",
        opd: "Dinas Pendidikan Kota Pasuruan",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.04",
        nama_barang: "Tanah Lapangan Untung Suropati",
        nibar: "NB-004-2017",
        luas: 8500.0,
        alamat:
          "Jl. Untung Suropati, Kel. Pekuncen, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 12750000000,
        no_sertifikat: "HP-005/Pekuncen",
        tanggal: "2017-11-05",
        opd: "Dinas Pemuda dan Olahraga",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.05",
        nama_barang: "Tanah Pasar Kebonsari",
        nibar: "NB-005-2016",
        luas: 4200.0,
        alamat:
          "Jl. Pasar Kebonsari No. 1, Kel. Kebonsari, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 8400000000,
        no_sertifikat: "HP-007/Kebonsari",
        tanggal: "2016-05-20",
        opd: "Dinas Perdagangan",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.06",
        nama_barang: "Tanah RSUD dr. R. Soedarsono",
        nibar: "NB-006-2015",
        luas: 15000.0,
        alamat:
          "Jl. Dr. Wahidin Sudirohusodo No. 4, Kel. Sekargadung, Kec. Bugul Kidul, Kota Pasuruan",
        nilai_perolehan: 37500000000,
        no_sertifikat: "HP-015/Sekargadung",
        tanggal: "2015-09-12",
        opd: "RSUD dr. R. Soedarsono",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.07",
        nama_barang: "Tanah Kantor Kecamatan Gadingrejo",
        nibar: "NB-007-2021",
        luas: 1800.0,
        alamat:
          "Jl. Hayam Wuruk No. 8, Kel. Gentong, Kec. Gadingrejo, Kota Pasuruan",
        nilai_perolehan: 3600000000,
        no_sertifikat: "HP-020/Gentong",
        tanggal: "2021-02-28",
        opd: "Kecamatan Gadingrejo",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.08",
        nama_barang: "Tanah Terminal Blandongan",
        nibar: "NB-008-2014",
        luas: 6000.0,
        alamat:
          "Jl. Ahmad Yani No. 100, Kel. Blandongan, Kec. Bugul Kidul, Kota Pasuruan",
        nilai_perolehan: 9000000000,
        no_sertifikat: "HP-025/Blandongan",
        tanggal: "2014-06-30",
        opd: "Dinas Perhubungan",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.09",
        nama_barang: "Tanah TPA Blandongan",
        nibar: "NB-009-2013",
        luas: 25000.0,
        alamat:
          "Jl. TPA Blandongan, Kel. Blandongan, Kec. Bugul Kidul, Kota Pasuruan",
        nilai_perolehan: 12500000000,
        no_sertifikat: "HP-030/Blandongan",
        tanggal: "2013-08-15",
        opd: "Dinas Lingkungan Hidup",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.10",
        nama_barang: "Tanah SMPN 1 Kota Pasuruan",
        nibar: "NB-010-2012",
        luas: 5600.0,
        alamat:
          "Jl. Balaikota No. 22, Kel. Purworejo, Kec. Purworejo, Kota Pasuruan",
        nilai_perolehan: 11200000000,
        no_sertifikat: "HP-035/Purworejo",
        tanggal: "2012-04-10",
        opd: "Dinas Pendidikan Kota Pasuruan",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.11",
        nama_barang: "Tanah Gedung DPRD Kota Pasuruan",
        nibar: "NB-011-2011",
        luas: 3200.0,
        alamat:
          "Jl. Pahlawan No. 50, Kel. Karanganyar, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 9600000000,
        no_sertifikat: "HP-040/Karanganyar",
        tanggal: "2011-10-20",
        opd: "Sekretariat DPRD",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.12",
        nama_barang: "Tanah Balai Kota Pasuruan",
        nibar: "NB-012-2010",
        luas: 4800.0,
        alamat:
          "Jl. Alun-alun No. 1, Kel. Purworejo, Kec. Purworejo, Kota Pasuruan",
        nilai_perolehan: 24000000000,
        no_sertifikat: "HP-001/Purworejo",
        tanggal: "2010-01-05",
        opd: "Sekretariat Daerah",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.13",
        nama_barang: "Tanah Taman Kota Pasuruan",
        nibar: "NB-013-2022",
        luas: 7200.0,
        alamat:
          "Jl. Soekarno Hatta, Kel. Tembokrejo, Kec. Purworejo, Kota Pasuruan",
        nilai_perolehan: 10800000000,
        no_sertifikat: "HP-045/Tembokrejo",
        tanggal: "2022-06-01",
        opd: "Dinas Perumahan dan Kawasan Permukiman",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
      {
        kode_barang: "01.01.11.04.14",
        nama_barang: "Tanah Kantor Dinas Sosial",
        nibar: "NB-014-2019",
        luas: 900.0,
        alamat:
          "Jl. WR. Supratman No. 15, Kel. Bangilan, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 1800000000,
        no_sertifikat: "HP-050/Bangilan",
        tanggal: "2019-12-10",
        opd: "Dinas Sosial",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.admin_bpka,
      },
      {
        kode_barang: "01.01.11.04.15",
        nama_barang: "Tanah Makam Umum Kepel",
        nibar: "NB-015-2008",
        luas: 32000.0,
        alamat: "Jl. Kepel, Kel. Kepel, Kec. Panggungrejo, Kota Pasuruan",
        nilai_perolehan: 6400000000,
        no_sertifikat: "HP-055/Kepel",
        tanggal: "2008-03-25",
        opd: "Dinas Lingkungan Hidup",
        pemegang: "Pemerintah Kota Pasuruan",
        created_by: createdUsers.bpka,
      },
    ];

    for (const item of pusatDataItems) {
      await PusatData.create(item);
    }
    console.log(`  ✅ Created ${pusatDataItems.length} Pusat Data items`);

    // ===== SEED ASET (BPN) =====
    console.log("\n📦 Seeding Aset (BPN)...");
    const asetItems = [
      {
        kode_aset: "BPN-PSR-001",
        nama_aset: "Tanah Kantor Kelurahan Purworejo",
        lokasi: "Jl. Panglima Sudirman No. 10, Purworejo",
        koordinat_lat: -7.6455,
        koordinat_long: 112.9075,
        luas: 1250.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 2500000000,
        tahun_perolehan: 2000,
        nomor_sertifikat: "HM-001/Purworejo/2000",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "2000-06-15",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Purworejo",
        desa_kelurahan: "Purworejo",
        luas_lapangan: 1248.5,
        batas_utara: "Jl. Panglima Sudirman",
        batas_selatan: "Tanah Milik H. Ahmad",
        batas_timur: "Gang Mawar",
        batas_barat: "Kantor Pos",
        penggunaan_saat_ini: "Kantor Kelurahan",
        kode_bmd: "01.01.11.04.01",
        nilai_buku: 2500000000,
        nilai_njop: 2200000000,
        sk_penetapan: "SK Walikota No. 188/2000",
        opd_pengguna: "Kelurahan Purworejo",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-002",
        nama_aset: "Tanah Lapangan Untung Suropati",
        lokasi: "Jl. Untung Suropati, Pekuncen",
        koordinat_lat: -7.6478,
        koordinat_long: 112.9045,
        luas: 8500.0,
        status: "Aktif",
        jenis_aset: "Tanah Fasilitas Umum",
        nilai_aset: 12750000000,
        tahun_perolehan: 1985,
        nomor_sertifikat: "HP-005/Pekuncen/1985",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1985-03-20",
        riwayat_perolehan: "Hibah",
        status_hukum: "Bersih",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Pekuncen",
        luas_lapangan: 8497.0,
        batas_utara: "Jl. Untung Suropati",
        batas_selatan: "Perumahan Penduduk",
        batas_timur: "Jl. HOS Cokroaminoto",
        batas_barat: "SD Negeri Pekuncen 1",
        penggunaan_saat_ini: "Lapangan Olahraga",
        kode_bmd: "01.01.11.04.04",
        nilai_buku: 12750000000,
        nilai_njop: 11000000000,
        sk_penetapan: "SK Walikota No. 100/1985",
        opd_pengguna: "Dinas Pemuda dan Olahraga",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-003",
        nama_aset: "Tanah eks HGU PT. Bogasari",
        lokasi: "Jl. Nusantara, Gadingrejo",
        koordinat_lat: -7.632,
        koordinat_long: 112.912,
        luas: 12000.0,
        status: "Bermasalah",
        jenis_masalah: "Sengketa",
        jenis_aset: "Tanah Industri",
        nilai_aset: 18000000000,
        tahun_perolehan: 2010,
        nomor_sertifikat: "HGB-101/Gadingrejo/2010",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Sengketa batas dengan pihak swasta, proses mediasi berlangsung di BPN Provinsi",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Sengketa - PT. Bogasari / Pemkot",
        tanggal_sertifikat: "2010-08-20",
        riwayat_perolehan: "Tukar Menukar",
        status_hukum: "Dalam Sengketa",
        kecamatan: "Gadingrejo",
        desa_kelurahan: "Gadingrejo",
        luas_lapangan: 11850.0,
        batas_utara: "Sungai Gembong",
        batas_selatan: "Jl. Nusantara",
        batas_timur: "Tanah PT. Bogasari",
        batas_barat: "Perumahan Gadingrejo Indah",
        penggunaan_saat_ini: "Lahan Kosong Bersengketa",
        kode_bmd: "01.01.11.04.20",
        nilai_buku: 18000000000,
        nilai_njop: 15600000000,
        sk_penetapan: "-",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-004",
        nama_aset: "Tanah Pasar Kebonsari",
        lokasi: "Jl. Pasar Kebonsari No. 1, Kebonsari",
        koordinat_lat: -7.65,
        koordinat_long: 112.91,
        luas: 4200.0,
        status: "Aktif",
        jenis_aset: "Tanah Pasar",
        nilai_aset: 8400000000,
        tahun_perolehan: 1990,
        nomor_sertifikat: "HP-007/Kebonsari/1990",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1990-05-10",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Kebonsari",
        luas_lapangan: 4195.0,
        batas_utara: "Jl. Pasar Kebonsari",
        batas_selatan: "Sungai",
        batas_timur: "Toko Milik Pak Slamet",
        batas_barat: "Gang Melati",
        penggunaan_saat_ini: "Pasar Tradisional",
        kode_bmd: "01.01.11.04.05",
        nilai_buku: 8400000000,
        nilai_njop: 7200000000,
        sk_penetapan: "SK Walikota No. 055/1990",
        opd_pengguna: "Dinas Perdagangan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "BPN-PSR-005",
        nama_aset: "Tanah RSUD dr. R. Soedarsono",
        lokasi: "Jl. Dr. Wahidin Sudirohusodo No. 4, Sekargadung",
        koordinat_lat: -7.658,
        koordinat_long: 112.92,
        luas: 15000.0,
        status: "Aktif",
        jenis_aset: "Tanah Kesehatan",
        nilai_aset: 37500000000,
        tahun_perolehan: 1975,
        nomor_sertifikat: "HP-015/Sekargadung/1975",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1975-12-01",
        riwayat_perolehan: "Hibah",
        status_hukum: "Bersih",
        kecamatan: "Bugul Kidul",
        desa_kelurahan: "Sekargadung",
        luas_lapangan: 14980.0,
        batas_utara: "Jl. Dr. Wahidin Sudirohusodo",
        batas_selatan: "Perumahan Penduduk",
        batas_timur: "Jl. Letjen S. Parman",
        batas_barat: "Sawah Milik Pak Darmo",
        penggunaan_saat_ini: "Rumah Sakit Umum Daerah",
        kode_bmd: "01.01.11.04.06",
        nilai_buku: 37500000000,
        nilai_njop: 32000000000,
        sk_penetapan: "SK Walikota No. 012/1975",
        opd_pengguna: "RSUD dr. R. Soedarsono",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-006",
        nama_aset: "Tanah Bekas Pabrik Gula Redjo Agung",
        lokasi: "Jl. Sultan Agung, Panggungrejo",
        koordinat_lat: -7.64,
        koordinat_long: 112.9,
        luas: 22000.0,
        status: "Indikasi Bermasalah",
        jenis_aset: "Tanah Industri",
        nilai_aset: 55000000000,
        tahun_perolehan: 2005,
        nomor_sertifikat: "HGB-050/Panggungrejo/2005",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Indikasi tumpang tindih sertifikat dengan tanah masyarakat, perlu verifikasi lapangan",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Pemerintah Kota Pasuruan (Pengalihan dari PTPN XI)",
        tanggal_sertifikat: "2005-04-28",
        riwayat_perolehan: "Pengalihan",
        status_hukum: "Perlu Verifikasi",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Panggungrejo",
        luas_lapangan: 21500.0,
        batas_utara: "Jl. Sultan Agung",
        batas_selatan: "Sungai Gembong",
        batas_timur: "Perkampungan Warga RT 05",
        batas_barat: "Jl. Kartini",
        penggunaan_saat_ini: "Lahan Kosong (sebagian dipakai warga)",
        kode_bmd: "01.01.11.04.25",
        nilai_buku: 55000000000,
        nilai_njop: 48000000000,
        sk_penetapan: "SK Walikota No. 200/2005",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-007",
        nama_aset: "Tanah SDN Kandangsapi 1",
        lokasi: "Jl. Veteran No. 45, Kandangsapi",
        koordinat_lat: -7.653,
        koordinat_long: 112.925,
        luas: 3500.0,
        status: "Aktif",
        jenis_aset: "Tanah Pendidikan",
        nilai_aset: 5250000000,
        tahun_perolehan: 1980,
        nomor_sertifikat: "HP-012/Kandangsapi/1980",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1980-07-15",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Bugul Kidul",
        desa_kelurahan: "Kandangsapi",
        luas_lapangan: 3498.0,
        batas_utara: "Jl. Veteran",
        batas_selatan: "Makam Umum",
        batas_timur: "Rumah Warga",
        batas_barat: "Gang Merdeka",
        penggunaan_saat_ini: "Sekolah Dasar",
        kode_bmd: "01.01.11.04.03",
        nilai_buku: 5250000000,
        nilai_njop: 4500000000,
        sk_penetapan: "SK Walikota No. 075/1980",
        opd_pengguna: "Dinas Pendidikan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "BPN-PSR-008",
        nama_aset: "Tanah Pelabuhan Rakyat Pasuruan",
        lokasi: "Jl. Pelabuhan, Ngemplakrejo",
        koordinat_lat: -7.628,
        koordinat_long: 112.915,
        luas: 18000.0,
        status: "Bermasalah",
        jenis_masalah: "Konflik",
        jenis_aset: "Tanah Pelabuhan",
        nilai_aset: 45000000000,
        tahun_perolehan: 1970,
        nomor_sertifikat: "HP-060/Ngemplakrejo/1970",
        status_sertifikat: "Dalam Proses",
        keterangan:
          "Konflik pemanfaatan lahan antara Pemkot dengan nelayan dan pengelola tambak",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1970-01-10",
        riwayat_perolehan: "Hibah",
        status_hukum: "Dalam Konflik",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Ngemplakrejo",
        luas_lapangan: 17200.0,
        batas_utara: "Selat Madura",
        batas_selatan: "Jl. Pelabuhan",
        batas_timur: "Muara Sungai",
        batas_barat: "Tambak Ikan",
        penggunaan_saat_ini: "Pelabuhan Rakyat & Tambak",
        kode_bmd: "01.01.11.04.30",
        nilai_buku: 45000000000,
        nilai_njop: 39000000000,
        sk_penetapan: "SK Walikota No. 005/1970",
        opd_pengguna: "Dinas Perhubungan",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-009",
        nama_aset: "Tanah Taman Kota Depan Alun-alun",
        lokasi: "Jl. Alun-alun Utara, Purworejo",
        koordinat_lat: -7.644,
        koordinat_long: 112.906,
        luas: 3800.0,
        status: "Aktif",
        jenis_aset: "Tanah Ruang Terbuka Hijau",
        nilai_aset: 7600000000,
        tahun_perolehan: 1960,
        nomor_sertifikat: "HP-002/Purworejo/1960",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1960-08-17",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Purworejo",
        desa_kelurahan: "Purworejo",
        luas_lapangan: 3795.0,
        batas_utara: "Jl. Alun-alun Utara",
        batas_selatan: "Masjid Agung Al-Anwar",
        batas_timur: "Jl. Alun-alun Timur",
        batas_barat: "Jl. Alun-alun Barat",
        penggunaan_saat_ini: "Taman Kota & RTH",
        kode_bmd: "01.01.11.04.35",
        nilai_buku: 7600000000,
        nilai_njop: 6500000000,
        sk_penetapan: "SK Walikota No. 001/1960",
        opd_pengguna: "Dinas Perumahan dan Kawasan Permukiman",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "BPN-PSR-010",
        nama_aset: "Tanah Kawasan Industri Blandongan",
        lokasi: "Jl. Raya Blandongan, Blandongan",
        koordinat_lat: -7.662,
        koordinat_long: 112.93,
        luas: 35000.0,
        status: "Diblokir",
        jenis_masalah: "Berperkara",
        jenis_aset: "Tanah Industri",
        nilai_aset: 70000000000,
        tahun_perolehan: 2015,
        nomor_sertifikat: "HGB-200/Blandongan/2015",
        status_sertifikat: "Diblokir",
        keterangan:
          "Tanah diblokir karena perkara perdata di Pengadilan Negeri Pasuruan No. 45/PDT/2023/PN.PSR",
        jenis_hak: "Hak Guna Bangunan",
        atas_nama: "Dalam Perkara - Pemkot vs Developer",
        tanggal_sertifikat: "2015-11-30",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Berperkara di Pengadilan",
        kecamatan: "Bugul Kidul",
        desa_kelurahan: "Blandongan",
        luas_lapangan: 34500.0,
        batas_utara: "Jl. Raya Blandongan",
        batas_selatan: "Lahan Pertanian",
        batas_timur: "Sungai Kedung Larangan",
        batas_barat: "Perumahan Blandongan",
        penggunaan_saat_ini: "Diblokir - Tidak Dapat Digunakan",
        kode_bmd: "01.01.11.04.40",
        nilai_buku: 70000000000,
        nilai_njop: 60000000000,
        sk_penetapan: "SK Walikota No. 300/2015 (Diblokir)",
        opd_pengguna: "-",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-011",
        nama_aset: "Tanah Balai Kota Pasuruan",
        lokasi: "Jl. Alun-alun No. 1, Purworejo",
        koordinat_lat: -7.6445,
        koordinat_long: 112.9065,
        luas: 4800.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 24000000000,
        tahun_perolehan: 1950,
        nomor_sertifikat: "HP-001/Purworejo/1950",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1950-01-01",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Purworejo",
        desa_kelurahan: "Purworejo",
        luas_lapangan: 4798.0,
        batas_utara: "Jl. Alun-alun",
        batas_selatan: "Jl. Veteran",
        batas_timur: "Kantor DPRD",
        batas_barat: "Pendopo Walikota",
        penggunaan_saat_ini: "Kantor Walikota Pasuruan",
        kode_bmd: "01.01.11.04.12",
        nilai_buku: 24000000000,
        nilai_njop: 20000000000,
        sk_penetapan: "SK Walikota No. 001/1950",
        opd_pengguna: "Sekretariat Daerah",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-012",
        nama_aset: "Tanah Puskesmas Kebonsari",
        lokasi: "Jl. Dr. Wahidin No. 32, Kebonsari",
        koordinat_lat: -7.651,
        koordinat_long: 112.911,
        luas: 2100.5,
        status: "Aktif",
        jenis_aset: "Tanah Kesehatan",
        nilai_aset: 4200000000,
        tahun_perolehan: 1995,
        nomor_sertifikat: "HP-003/Kebonsari/1995",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1995-09-01",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Kebonsari",
        luas_lapangan: 2098.0,
        batas_utara: "Jl. Dr. Wahidin",
        batas_selatan: "Rumah Warga",
        batas_timur: "Gang Kenari",
        batas_barat: "Apotek Sehat",
        penggunaan_saat_ini: "Puskesmas",
        kode_bmd: "01.01.11.04.02",
        nilai_buku: 4200000000,
        nilai_njop: 3800000000,
        sk_penetapan: "SK Walikota No. 090/1995",
        opd_pengguna: "Dinas Kesehatan",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "BPN-PSR-013",
        nama_aset: "Tanah Gedung DPRD Kota Pasuruan",
        lokasi: "Jl. Pahlawan No. 50, Karanganyar",
        koordinat_lat: -7.646,
        koordinat_long: 112.908,
        luas: 3200.0,
        status: "Aktif",
        jenis_aset: "Tanah Perkantoran",
        nilai_aset: 9600000000,
        tahun_perolehan: 1988,
        nomor_sertifikat: "HP-040/Karanganyar/1988",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1988-04-21",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Karanganyar",
        luas_lapangan: 3198.0,
        batas_utara: "Jl. Pahlawan",
        batas_selatan: "Perumahan Karanganyar",
        batas_timur: "Taman Mini",
        batas_barat: "Bank Jatim",
        penggunaan_saat_ini: "Gedung DPRD",
        kode_bmd: "01.01.11.04.11",
        nilai_buku: 9600000000,
        nilai_njop: 8400000000,
        sk_penetapan: "SK Walikota No. 045/1988",
        opd_pengguna: "Sekretariat DPRD",
        created_by: createdUsers.admin_bpn,
      },
      {
        kode_aset: "BPN-PSR-014",
        nama_aset: "Tanah Makam Umum Kepel",
        lokasi: "Jl. Kepel, Kepel",
        koordinat_lat: -7.638,
        koordinat_long: 112.898,
        luas: 32000.0,
        status: "Aktif",
        jenis_aset: "Tanah Makam",
        nilai_aset: 6400000000,
        tahun_perolehan: 1955,
        nomor_sertifikat: "HP-055/Kepel/1955",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1955-06-01",
        riwayat_perolehan: "Warisan Kolonial",
        status_hukum: "Bersih",
        kecamatan: "Panggungrejo",
        desa_kelurahan: "Kepel",
        luas_lapangan: 31800.0,
        batas_utara: "Jl. Kepel",
        batas_selatan: "Sawah",
        batas_timur: "Perumahan Warga",
        batas_barat: "Jl. Sunan Ampel",
        penggunaan_saat_ini: "Makam Umum",
        kode_bmd: "01.01.11.04.15",
        nilai_buku: 6400000000,
        nilai_njop: 5500000000,
        sk_penetapan: "SK Walikota No. 003/1955",
        opd_pengguna: "Dinas Lingkungan Hidup",
        created_by: createdUsers.bpn,
      },
      {
        kode_aset: "BPN-PSR-015",
        nama_aset: "Tanah Terminal Blandongan",
        lokasi: "Jl. Ahmad Yani No. 100, Blandongan",
        koordinat_lat: -7.66,
        koordinat_long: 112.928,
        luas: 6000.0,
        status: "Aktif",
        jenis_aset: "Tanah Transportasi",
        nilai_aset: 9000000000,
        tahun_perolehan: 1992,
        nomor_sertifikat: "HP-025/Blandongan/1992",
        status_sertifikat: "Terdaftar",
        jenis_hak: "Hak Pakai",
        atas_nama: "Pemerintah Kota Pasuruan",
        tanggal_sertifikat: "1992-10-10",
        riwayat_perolehan: "Pembelian",
        status_hukum: "Bersih",
        kecamatan: "Bugul Kidul",
        desa_kelurahan: "Blandongan",
        luas_lapangan: 5990.0,
        batas_utara: "Jl. Ahmad Yani",
        batas_selatan: "Lahan Pertanian",
        batas_timur: "Bengkel Jaya Motor",
        batas_barat: "Rumah Warga RT 03",
        penggunaan_saat_ini: "Terminal Bus Kota",
        kode_bmd: "01.01.11.04.08",
        nilai_buku: 9000000000,
        nilai_njop: 7800000000,
        sk_penetapan: "SK Walikota No. 110/1992",
        opd_pengguna: "Dinas Perhubungan",
        created_by: createdUsers.admin_bpn,
      },
    ];

    for (const item of asetItems) {
      await Aset.create(item);
    }
    console.log(`  ✅ Created ${asetItems.length} Aset items`);

    // ===== SUMMARY =====
    console.log("\n" + "=".repeat(60));
    console.log("✅ LOCAL DATABASE SEEDED SUCCESSFULLY!");
    console.log("=".repeat(60));
    console.log(`\n📊 Summary:`);
    console.log(`   Users:       ${users.length}`);
    console.log(`   Pusat Data:  ${pusatDataItems.length} (BPKA)`);
    console.log(`   Aset:        ${asetItems.length} (BPN)`);
    console.log(`\n🔑 Credentials:`);
    console.log("   admin_bpka / admin123");
    console.log("   admin_bpn   / admin123");
    console.log("   bpka       / bpka123");
    console.log("   bpn_user    / bpn123");
    console.log("=".repeat(60));

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
    console.error(error);
    process.exit(1);
  }
}

seedAll();
